runtime: python27
api_version: 1
threadsafe: false

handlers:
  - url: /
    static_files: static/index.html
    upload: static/index.html

  - url: /dist/.*
    script: redirect.py

  - url: /(.*\.js(\.map)?)
    static_files: static/javascript/\1
    upload: static/(.*\.js(\.map)?)

  - url: /(.*\.css)
    static_files: static/css/\1
    upload: static/(.*\.css)

  - url: /.*
    static_files: static/404.html
    upload: static/404.html
