application: cdn
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
  - url: /
    static_files: static/index.html
    upload: static/index.html

  - url: /(.*\.js)
    static_files: static/javascript/\1
    upload: static/(.*\.js)

  - url: /.*
    script: errors.py
