service: cdn
runtime: python27
api_version: 1
threadsafe: false

handlers:
  - url: /
    static_files: static/index.html
    upload: static/index.html
    mime_type: text/html; charset=UTF-8

  - url: /dist/(.*\.js(\.map)?)
    static_files: static/javascript/\1
    upload: static/(.*\.js(\.map)?)
    mime_type: application/javascript; charset=UTF-8

  - url: /(.*?)/(.*)
    script: dynamic_files.app

  - url: /(.*\.js(\.map)?)
    static_files: static/javascript/\1
    upload: static/(.*\.js(\.map)?)
    mime_type: application/javascript; charset=UTF-8

  - url: /(.*\.css)
    static_files: static/css/\1
    upload: static/(.*\.css)
    mime_type: text/css; charset=UTF-8

  - url: /.*
    static_files: static/404.html
    upload: static/404.html
    mime_type: text/html; charset=UTF-8

libraries:
- name: webapp2
  version: latest
