version: 2

main_branch_only: &main_branch_only
  filters:
    branches:
      only:
        - master
        - gzip

jobs:
  deploy:
    docker:
    - image: groupbyinc/cdn-deployment:gzip-refactor
    working_directory: /workspace
    environment:
      GCLOUD_PROJECT: 'groupby-cloud-1701'
    steps:
    - checkout
    - run: deploy.sh

workflows:
  version: 2
  deploy:
    jobs:
    - deploy:
        <<: *main_branch_only
        context: org-global
